services:
  audio-detection-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    ports:
      - "8000:8000"
    volumes:
      - audio-uploads:/tmp/audio_uploads
      - ../models:/app/models
    networks:
      - audio-detection-network
    environment:
      # Proxy settings
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      # Whisper configuration
      - WHISPER_MODEL=small
      - UPLOAD_DIR=/tmp/audio_uploads
      # VOSK configuration
      - VOSK_MODEL_PATH=/app/models/vosk-model-ar-0.22
      - VOSK_SAMPLE_RATE=16000
      # Queue configuration
      - QUEUE_TYPE=mqtt
      - QUEUE_ENABLED=true
      # Redis settings (used when QUEUE_TYPE=redis)
      - REDIS_URL=redis://redis:6379/0
      # MQTT settings (used when QUEUE_TYPE=mqtt)
      - MQTT_BROKER_URL=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_QOS=0
      - MQTT_RETAIN=false
    restart: unless-stopped
    # Memory limits
    mem_limit: 8g
    mem_reservation: 2g
    depends_on:
      - redis
      - mosquitto

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - audio-detection-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSockets
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - audio-detection-network
    restart: unless-stopped

volumes:
  audio-uploads:
  redis-data:
  mosquitto-data:
  mosquitto-log:

networks:
  audio-detection-network:
    driver: bridge
    name: audio-detection-network