services:
  whisper-api:
    platform: linux/arm64  # Specifically for Apple Silicon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - whisper-data:/tmp/whisper_uploads
      - ./app.py:/app/app.py
    environment:
      - WHISPER_MODEL=small
      - CACHE_MODELS=true
      - REDIS_URL=redis://redis:6379/0
      - REDIS_ENABLED=true
    restart: unless-stopped
    # Memory limits
    mem_limit: 8g
    mem_reservation: 2g
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  whisper-data:
  redis-data: